services:
  - type: web
    name: live-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: TWITCH_CANAL
        sync: false
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_REFRESH_TOKEN
        sync: false
      - key: BLIZZARD_CLIENT_ID
        sync: false
      - key: BLIZZARD_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_VIDEO_ID
        sync: false
      - key: TOKEN_FILE
        value: token.json
      - key: CLIENT_SECRETS_FILE
        value: client_secret.json
      - key: SPREADSHEET_ID
        sync: false
      - key: SHEET_NAME
        value: Player_status
      - key: CREDENTIALS_FILE
        value: credentials.json
      - key: API_KEY
        sync: false
      - key: YOUTUBE_TOKEN_CONTENT
        sync: false
      - key: CLIENT_SECRET_JSON
        sync: false
      - key: GOOGLE_CREDENTIALS_CONTENT
        sync: false
      - key: TWITCH_TOKEN_SCOPES
        value: "channel:read:polls channel:manage:polls chat:read chat:edit"
